### ISSUE TITLE
Routing to multiple Angular 7 projects in Express based on JWT authentication and Role

### ISSUE THREAD

**Issue by krish512** [expressjs/discussions#76] opened 2019-02-12 11:34 UTC
have created an Angular 7 project which has multiple applications for different roles, like admin, user, editor, etc. each have different components and view.

A logged in user will land on its user role application, where as any guest user will land on 'website' application which has login and signup page.

My problem is to route using express to different angular applications based on user role determined during authentication. This works with one angular application, but doesn't work with multiple angular application

**Comment by dougwilson** [comment] 2019-02-13 05:13
Duplicate of https://github.com/expressjs/express/issues/3879

**Closed by dougwilson** 2019-02-13 05:13 UTC
