### ISSUE TITLE
Express TC Meeting - 2016-04-20

### ISSUE THREAD

**Issue by crandmck** [expressjs/discussions#14] opened 2016-04-19 21:45 UTC
## Who

Invited: 
- @expressjs/express-tc 
- @mikeal (tsc mentor)
- @jasnell (tsc mentor) 
- @wesleytodd (observer)
- @tunniclm (observer)
- @sjanuary (observer)
- @ritch (observer)
- @gabeio (observer)
## When

April 20th, 2016 - [23:30 UTC ](https://www.google.com/search?q=23%3A30+UTC&oq=23%3A30+UTC)
## Where

Google Hangouts:

Link for Participants: https://plus.google.com/hangouts/_/hoaevent/AP36tYdM_bgNKc1pXakhc8lqt_VHGS1Jea6WPR2irly_T-JSZAmY0g?hl=en&authuser=0

Link for Observers: https://plus.google.com/events/c42doafcrpf6pta39jskgrho7t4
## Agenda
- Node.js 6.0 release & compatibility

**Comment by LinusU** [comment] 2016-04-20 20:39
I'm sorry to say that I need to sit this one out :( it's a bit hard for me to make every meeting since they are at 01:30 in the night for me, but I hope to be around for the next one 👌

**Comment by jasnell** [comment] 2016-04-20 22:23
Just wanted to check-in. It's been a few weeks since I've been able to join the calls. Does the @expressjs/express-tc feel there is any need for either of the TSC mentors (myself or @mikeal) to be on this weeks call? Are there any issues that need clarification or input from either of us?

**Comment by crandmck** [comment] 2016-04-20 22:35
@dougwilson Are you available for this meeting?  Do you have any agenda items?

@jasnell For my part, I don't have anything specifically for mentors.  Can't speak for anyone else of course.

**Comment by jasnell** [comment] 2016-04-20 22:36
Ok, well I'll hold off on dialing in but I will be online. Mention me in a comment here and I'll jump in if necessary.

**Comment by jasnell** [comment] 2016-04-20 22:38
oh! Node.js v6 is scheduled to hit on Tuesday. We have a few additional changes that are pending that could land before then. One of which is https://github.com/nodejs/node/pull/6102 which impacts the HTTP `headers` property. I'd appreciate if we could get a review on what the impact of this change would be. Also, would be great to know if anyone has seen any other regressions.

**Comment by dougwilson** [comment] 2016-04-20 22:57
Sorry, I was just on my way home :) Yes, I'll be there, and will be making the Google Hangout in a few minutes so we'll have it :) I was thinking a bit about topics today, since there wasn't any that came up yet, and Node.js 6.0 I think is worth going over (a good one to do at a TC level) and probably a couple others.

**Comment by crandmck** [comment] 2016-04-20 22:58
Great, so @dougwilson just to confirm: You've solved your PC tech issue, and you don't need me to host the meeting on zoom.us?

**Comment by dougwilson** [comment] 2016-04-20 23:00
@crandmck yep!

**Comment by jonathanong** [comment] 2016-04-20 23:01
how do i hop on? is there a google hangout?

**Comment by dougwilson** [comment] 2016-04-20 23:28
Link for Observers: https://plus.google.com/events/c42doafcrpf6pta39jskgrho7t4

@jonathanong I'll have the link for participants in just a minute, after I install Chrome apparently.

**Comment by dougwilson** [comment] 2016-04-20 23:34
Link for Participants: https://plus.google.com/hangouts/_/hoaevent/AP36tYdM_bgNKc1pXakhc8lqt_VHGS1Jea6WPR2irly_T-JSZAmY0g?hl=en&authuser=0

**Comment by wesleytodd** [comment] 2016-04-21 00:13
Link to standard: https://github.com/feross/standard

Personally I help support the happiness, which does do the semicolons, but also uses tabs.  Semi-standard is the fork that uses semicolons: https://github.com/Flet/semistandard

**Comment by crandmck** [comment] 2016-04-21 00:18
Here are my limited notes.  Will consolidate with anything else added and create a md doe in this repo as Doug suggested.

Node v6 to be released next Tues:
- Will v6 be the next LTS?  Rand will try to find out from Bert.
- Run test suites on v6 on JSHTTP modules
- 4.14 Release will be forthcoming, after Node v6, so we can make any fixes in that release.  Will have a release based PR.

Delete the old redundant https://github.com/expressjs/express-api-docs repo - no objections.

Add to website something about TC meetings.  @crandmck will do this.

Create docs in this repo for meeting minutes

Discussion of doc translations - will take a look at proposed changes to Japanese
translations https://github.com/expressjs/expressjs.com/pull/620
and contributed Slovak trans.

5.0 release - work ongoing (might require Node 4+) 
Prob wont support http2 OOTB.
Discussion of TypeScript support

Discussion of using ESLint for contribs and possibly tests and also 
code style/rules (Blake suggested https://github.com/feross/standard)

**Comment by jasnell** [comment] 2016-04-21 00:28
Yes, v6 will be the next LTS, it won't transition to LTS tho until October. Between now and then we will still be actively landing semver-minor bumps and quite possibly v8 majors if there are no API/ABI breaking changes. v5 support will trail off over the coming few weeks. v4 will remain on the active LTS track until April 2017, after which it switches to maintenance.

Btw, in node core have a tool called citgm (https://github.com/nodejs/citgm) that runs ecosystem tests in our CI environment as part of our normal process. We can get all of the jshttp module into that. All it takes is a PR.

**Comment by LinusU** [comment] 2016-04-21 06:11
Huge +1 on [standard style](https://github.com/feross/standard) from me, we are already using it in multer and it's working great!

**Comment by hacksparrow** [comment] 2016-04-21 09:15
Thanks for the summary @crandmck.

**Comment by cdnadmin** [comment] 2016-05-02 21:25
Hey, guys, just a thought.  How about adding a wiki to this discussion repo to house final agenda, meeting minutes, etc for posterity and easy reference.  This helps streamline the communication about what's going on with Express, TC, etc without all the noise of GH issues discussions' back-and-forth.  :-)  ...albeit GH discussions' back-and-forth are definitely useful in some instances.

**Comment by intellix** [comment] 2016-05-08 08:56
Came here searching for http/2 goodness :) Using angular-cli, which is using SystemJS and ES6 module loading. To start a development server takes about 6 seconds to load around 600 files (insane!). I imagine with http/2 this will ease pain quite a bit.

What's the main pain point in supporting http/2 out of the box?

**Comment by wesleytodd** [comment] 2016-05-19 14:00
The recorded video: https://www.youtube.com/watch?v=8ZRRTVTtQ3U

**Comment by gireeshpunathil** [comment] 2020-03-25 06:01
meeting happened long back, closing. Please re-open if anything is outstanding here.

**Closed by gireeshpunathil** 2020-03-25 06:01 UTC
Labels: meeting
