### ISSUE TITLE
Use Github Discussions instead of a dedicated repository

### ISSUE THREAD

**Issue by ITAYC0HEN** [expressjs/discussions#143] opened 2020-12-24 12:29 UTC
GitHub [introduced](https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/) the [Discussions](https://docs.github.com/en/free-pro-team@latest/discussions/quickstart) features which can be an alternative to this repository.

![image](https://user-images.githubusercontent.com/20182642/103088718-4f515880-45f4-11eb-9238-756ebb84c118.png)

**Comment by dougwilson** [comment] 2020-12-24 12:57
Duplicate of #128

**Closed** 2020-12-24 12:57 UTC
