### ISSUE TITLE
expressjs.com transfer progress

### ISSUE THREAD

**Issue by jasnell** [expressjs/discussions#8] opened 2016-03-17 23:46 UTC
Tomorrow (Friday March 18th) I'll be looking into what steps are necessary to get the domain repo transferred. I'm not yet certain if there are any gotchas with regards to moving a repo with an associated Apex domain. I want to make sure that there are no hiccups in the site hosting before actually moving the repository.

I will use this issue to update on the progress.

/cc @expressjs/express-tc

**Comment by jasnell** [comment] 2016-03-23 22:20
I am currently waiting to here back from Github to confirm some information before I move the repository. Basically, I need to know if the DNS records will need to be updated when the repository is moved. If so, it's going to take a bit more time because I'll need to round up the person who can actually make those DNS changes. /cc @expressjs/express-tc

**Comment by jasnell** [comment] 2016-03-30 13:50
Ok, @expressjs/express-tc: so the short version is that yes, the DNS changes would need to be coordinated with the repository move. Thinking it over, I think what would likely make the most sense at this point is this:

1) rather than moving the repository, we create a fork of the strongloop/expressjs.com repository here and make sure that everything is working.
2) we can then get the DNS records switched to point at the expressjs/expressjs.com site rather than strongloop/expressjs.com.

This echoes the same process we followed for transitioning the nodejs.org website and the process was relatively painless. 

How does that sound?

**Comment by DavidTPate** [comment] 2016-03-30 14:00
Seems like the best plan to me. That way the lag time for the DNS change doesn't matter as either record that is received will send the user to working documentation.

**Comment by dougwilson** [comment] 2016-03-30 14:34
Won't this cause us to lose all the issues, pull requests and the history? All the commits have PR numbers in them, so it would be really sucky if we lost all that.

**Comment by dougwilson** [comment] 2016-03-30 14:35
I don't feel like having the website down for a bit even matters. If it does, just down the TTL on the domain to 5 minutes, move the repo, update the records, and re-up the TTL.

**Comment by hacksparrow** [comment] 2016-03-30 14:58
Also, the [CNAME](https://github.com/strongloop/expressjs.com/blob/gh-pages/CNAME) file is supposed to be unique in the whole of GitHub. Therefore, a cloned gh-pages site will not be up till the existing CNAME file is changed / deleted.

**Comment by DavidTPate** [comment] 2016-03-30 16:52
@dougwilson If the repository is cloned then we shouldn't lose the history. Now if we only copy the files itself, then yes we would lose the files. But we can [import](https://help.github.com/articles/importing-your-project-to-github/) the repo and it would be pulled over along with the history.

Definitely agree that history > slight downtime. But I don't believe that is a trade off we have to make.

**Comment by jasnell** [comment] 2016-03-30 17:35
We'll get the commit history but not the open issues and pull requests, so those would need to be managed. That said, there are currently only 16 open issues and 1 open pull request so the management burden is not that great. The strongloop/expressjs.com repository would not go away, it would essentially be treated as an archive.

Btw, I'm still working to track down the specific person who can make the necessary DNS changes on our side (@crandmck @rmg: if either of you know specifically who can do that, please let me know)

**Comment by dougwilson** [comment] 2016-03-30 17:52
> The strongloop/expressjs.com repository would not go away, it would essentially be treated as an archive.

I do not think keeping an ever-lasting fork is an acceptable solution in any way. The original repository *must* live in the `expressjs` organization unless we delete all repository history and start over again. The issue is that there are tons and ton of commits with `Merge pull request #<num> from <user>/<repo>`. Unless @jasnell or someone else is volunteering to rewrite the entire repository history to either remove those `#<num>` or rewrite them all to URLs, then it is not an acceptable solution.

**Comment by crandmck** [comment] 2016-03-30 18:07
I don't know much about importing/copying/transferring repos, but I would certainly like to keep the existing issues, PRs, and history intact if at all possible.  I agree with Doug that we shouldn't have any duplicate (or forked) repos.... If there is no other option and we want to keep an archive, I suppose we could make the existing strongloop/expressjs.com repo private just for reference purposes, but I would much prefer just transferring it to the expressjs org if that is possible.  

I didn't think this was going to be so hard :-(

**Comment by jasnell** [comment] 2016-03-30 18:11
We can still move the repo, it'll just take a bit longer to coordinate.
Bear with me :)

**Comment by rmg** [comment] 2016-03-30 18:11
To set up apex CNAMEs you need to use GitHub Pages ip addresses.. so none of that needs to change in order to transfer the repo to this org. It should all "just work".

**Comment by crandmck** [comment] 2016-04-15 16:02
@expressjs/express-tc  I'd like to go ahead with moving the expressjs.com repo from strongloop org to expressjs.  @jasnell said that was OK, even though he's still working on issues around the domain transfer.  My understanding is that the two operations are orthogonal.

According to https://help.github.com/articles/transferring-a-repository/#transferring-between-organizations:
> ...the person transferring the repository also needs to have owner or admin rights in the receiving organization. .... You can arrange this by asking the receiving organization to create a team with admin privileges with no repositories in it.

However, I'm not an owner in expressjs org (I am in the admin group in strongloop org). Could someone either make me an owner in expressjs or create team with admin privs in expressjs org and add me to it?

**Comment by dougwilson** [comment] 2016-04-15 16:07
@crandmck, I can make you an owner, but previously the requirement has been that you need to have 2FA setup on your account or provide a good reason for why it cannot be setup before being added as an Owner, for precaution.

**Comment by jasnell** [comment] 2016-04-15 16:11
Yeah, sorry, I ended up getting buried and let this slip. Once you have 2fa set up one of us can add you to the owners (you should be added anyway since you're on the TC :-)..)

**Comment by crandmck** [comment] 2016-04-15 16:14
I think @jasnell is going to to it.  I'll set up 2fa anyway soon.  But no need to wait...

**Comment by jasnell** [comment] 2016-04-15 16:19
Transferred! Created a new @expressjs/expressjs-com team to admin the repo and added @crandmck as a team maintainer so he can add anyone else that needs to be included. Also gave the @expressjs/express-tc permissions on the repo. Confirmed that the website is still up and running. Should be good to go now.

**Closed** 2016-04-15 16:19 UTC

**Comment by crandmck** [comment] 2016-04-15 16:22
Thanks @jasnell

**Comment by mikeal** [comment] 2016-04-18 17:28
FYI, there's a setting in the "org settings" that allows any org member to create new repos (without being the owner). We use this in the nodejs org, it's quite convenient.

**Comment by dougwilson** [comment] 2016-04-18 17:41
@mikeal, that is already enabled, I believe. GitHub still does not allow moving a repository from somewhere else into an organization unless you're an admin in both, even if you can create new repos in the destination organization.

More information can be found in https://help.github.com/articles/transferring-a-repository/ particularly:

> On the other end, the person transferring the repository also needs to have owner or admin rights in the receiving organization.

**Comment by mikeal** [comment] 2016-04-18 22:19
huh, I wonder why you need the extra permission, this is good to know though :)
